# NOTE: This action is only supported temporarily until out-of-band provenance
#       is supported in upstream npm.
# TODO(#1897): Remove this action.

name: "setup-npm"
description: "Install provenance-ready fork of npm"
runs:
  using: "composite"
  steps:
    - name: Clone npm fork
      id: clone-fork
      env:
        # This points to the slsa-framework/npm-cli oob-provenance branch
        # which contains patches to the v9.6.5 release of the npm cli.
        NPM_REMOTE_URL: "https://github.com/slsa-framework/npm-cli.git"
        NPM_GIT_SHA: "be87719832648731541cf6019c00320f479cafe5"
      run: |
        set -euo pipefail

        # Clone npm fork.
        node_path="$(readlink -m $(dirname "$(which node)"))"

        cd "${node_path}"
        mkdir -p node_modules/npm
        cd node_modules/npm
        git init
        git remote add origin "${NPM_REMOTE_URL}"

        # Fetch and checkout oob-provenance branch at pinned digest.
        git fetch --depth 1 origin "${NPM_GIT_SHA}"
        git checkout "${NPM_GIT_SHA}"

        # Install dependencies
        ./bin/npm ci

        # Output the path to the npm binary.
        echo "npm-path=${node_path}/node_modules/npm/bin" >>"${GITHUB_OUTPUT}"
