name: "Checkout a repository for a Node project"
description: "Checkout and setup the environment for a Node project"
inputs:
  repository:
    description: "Repository name with owner."
    required: false
    # Same default as https://github.com/actions/checkout/blob/main/action.yml#L6.
    default: ${{ github.repository }}
  ref:
    description: "A fully formed ref (refs/...) or SHA to checkout."
    required: false
    default: ${{ github.sha }}
  token:
    description: "The token to use."
    required: false
    # Same default as https://github.com/actions/checkout/blob/main/action.yml#L24.
    default: ${{ github.token }}
  node-version:
    description: "The Node version to use, as expected by https://github.com/actions/setup-node."
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout the repository with user ref
      # FIXME: update digest when #1005 is merged.
      # uses: slsa-framework/slsa-github-generator/.github/actions/secure-checkout@f348c29e4be53b8413640f1f2eabd3fbde249a15
      uses: ianlewis/slsa-github-generator/.github/actions/secure-checkout@secure-checkout-ref
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        token: ${{ inputs.token }}

    - name: Set up Node environment
      uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3.4.1
      with:
        node-version: ${{ inputs.node-version }}
