name: "Checkout a repository for a Node project"
description: "Checkout and setup the environment for a Node project"
inputs:
  repository:
    description: "Repository name with owner."
    required: false
    # Same default as https://github.com/actions/checkout/blob/main/action.yml#L6.
    default: ${{ github.repository }}
  sha:
    description: "The SHA to checkout."
    required: false
  token:
    description: "The token to use."
    required: false
    # Same default as https://github.com/actions/checkout/blob/main/action.yml#L24.
    default: ${{ github.token }}
  node-version:
    description: "The Node version to use, as expected by https://github.com/actions/setup-node."
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout the repository with user ref
      uses: slsa-framework/slsa-github-generator/.github/actions/secure-checkout@7d890e74a8b3cc26e78b0b23428026cc043a8d17
      with:
        repository: "${{ inputs.repository }}"
        sha: "${{ inputs.sha }}"
        token: "${{ inputs.token }}"

    - name: Set up Node environment
      uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3.4.1
      with:
        node-version: "${{ inputs.node-version }}"
