name: SLSA Node.js builder

permissions: {}

on:
  workflow_call:
    inputs:
      directory:
        description: "Sub-directory where package.json is located. Must be under the workspace."
        required: false
        type: string
        default: "."

      node-version:
        description: "Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0."
        required: false
        type: string

      node-version-file:
        description: "File containing the version Spec of the version to use.  Examples: .nvmrc, .node-version, .tool-versions."
        required: false
        type: string

      run-scripts:
        description: "An ordered list of scripts from the package.json file to run (comma separated). Example value: 'script1, script2'"
        required: false
        type: string

      # NOTE: the additional inputs below are to support additional
      # functionality of the workflow.
      rekor-log-public:
        description: "Allow publication of your repository name on the public Rekor log"
        required: false
        type: boolean
        default: false

    secrets:
      node-auth-token:
        description: "The npm registry auth token used to publish the package."
        required: true

jobs:
  slsa-setup:
    permissions:
      id-token: write # For token creation.
    outputs:
      slsa-token: ${{ steps.generate.outputs.slsa-token }}
    runs-on: ubuntu-latest
    steps:
      - name: Generate the token
        id: generate
        uses: slsa-framework/slsa-github-generator/actions/delegator/setup-token@main
        with:
          slsa-workflow-recipient: "delegator_generic_slsa3.yml"
          slsa-rekor-log-public: ${{ inputs.rekor-log-public }}
          slsa-runner-label: "ubuntu-latest"
          slsa-build-action-path: "./internal/nodejs-action"
          slsa-version: "v0.2"
          # TODO(#1575): mask sensitive fields.
          slsa-workflow-inputs: ${{ toJson(inputs) }}

  slsa-run:
    needs: [slsa-setup]
    permissions:
      id-token: write # For signing.
      contents: write # For asset uploads.
      packages: write # For publishing to GitHub packages.
    uses: slsa-framework/slsa-github-generator/.github/workflows/delegator_generic_slsa3.yml@main
    with:
      slsa-token: ${{ needs.slsa-setup.outputs.slsa-token }}

  # TODO(#1847): Use cleanup/finalize hook.
  slsa-publish:
    needs: [slsa-run]
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write # For asset uploads. Optional
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node environment
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: ${{ inputs.node-version }}
          node-version-file: ${{ inputs.node-version-file }}
          registry-url: "https://registry.npmjs.org"

      # NOTE: The attestation name has a rng value in it's name so we don't need to check for file collisions.
      - name: Download attestations
        id: attestation-download
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: ${{ needs.slsa-run.outputs.attestations-download-name }}

      - name: Download artifact
        id: package-download
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: "package.tgz"

      # TODO(#1680): verify the attestation before upload.
      # - name: Verify attestations
      #   env:
      #     SLSA_ATTESTATION_DOWNLOAD_NAME: ${{ needs.slsa-run.outputs.attestations-download-name }}
      #   run: |
      #     echo "download from $SLSA_ATTESTATION_DOWNLOAD_NAME"

      # TODO(#888): Publish to GitHub release.

      # TODO(#1669): Publish to npm. Note that we need to upload our own bundle to npm.
      # TODO(#1669): Use mainline version of npm
      - name: Clone npm fork
        id: clone-fork
        env:
          NPM_GIT_SHA: bc657b76f09cbdd5801e360633898b14a4bbc5e8
        run: |
          set -euo pipefail

          # Clone npm fork.
          cd "$(dirname "$(which node)")"
          mkdir -p node_modules/npm
          cd node_modules/npm
          git init
          git remote add origin https://github.com/ianlewis/cli.git

          # Fetch and checkout oob-provenance branch at pinned digest.
          git fetch --depth 1 "${NPM_GIT_SHA}"
          git checkout "${NPM_GIT_SHA}"

          # Install dependencies
          ./bin/npm ci

      # TODO(#1669): Use mainline version of npm
      # TODO(#1669): Generalize directory path checking. The same logic is needed in internal action.
      - name: Publish the package
        id: publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.node-auth-token }}
          ATTESTATION_DIR: ${{ steps.attestation-download.outputs.download-path }}
          ATTESTATION_NAME: ${{ fromJSON(needs.slsa-run.outputs.build-artifacts-outputs).attestation-name }}
          PACKAGE_DIR: ${{ steps.package-download.outputs.download-path }}
          PACKAGE_FILE_NAME: ${{ fromJSON(needs.slsa-run.outputs.build-artifacts-outputs).package-filename }}
          UNTRUSTED_DIRECTORY: ${{ inputs.directory }}
        run: |
          set -euo pipefail

          package_path="${PACKAGE_DIR}/${PACKAGE_FILE_NAME}"
          attestation_path="${ATTESTATION_DIR}/${ATTESTATION_NAME}.sigstore"

          # Run npm publish using npm fork.
          # TODO(#1829): Support the --access flag.
          "$(dirname "$(which node)")"/node_modules/npm/bin/npm publish "${package_path}" --access public --provenance "${attestation_path}"
