name: schedule verify-token wrapper

on:
  # Daily run.
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

permissions: read-all

env:
  GH_TOKEN: ${{ github.token }}
  ISSUE_REPOSITORY: ${{ github.repository }}

jobs:
  verify-token-e2e:
    permissions:
      contents: read
      id-token: write
      issues: write
    uses: ./.github/workflows/e2e.verify-token.reusable.yml
