name: markdown

on:
  push:
    branches: [main, "*"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [main]
  workflow_dispatch:

permissions:
  # Needed to check out the repo.
  contents: read

jobs:
  markdow-toc:
    name: markdown-toc
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js 16
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3.5.1
        with:
          node-version: 16
      - name: Install markdown-toc
        run: npm install markdown-toc
      - name: markdown-toc
        # TODO: run script to run markdown-toc on all markdown files in the repo and check if they changed.
